-- Active: 1788351678322@@127.0.0.1@3306@smartcoffee_dml_jaco_souza

-- CONSULTA DE DADOS

INSERT INTO CLIENTE (NOME, EMAIL, TELEFONE, CIDADE, ATIVO) VALUES
('WLADIMIR EDSON','EDSON@GMAIL.COM','1999999432','PARIS',TRUE); AFFECTEDROWS

-- SERVE PARA A VISUALIZAÇÃO DAS TABELAS
SELECT * FROM CLIENTE

-- EMPLO DE ESTRUTURA SIMPLES DE SELECT
-- SELECT COLUNA --> AQUI VOCE SELECIONA A COLUNA DO INSERT INTO
-- FRAOM TABELE; --> AQUI VOCE SELECIONA A TABELA QUE FOI DITA NO INSERT INTO

-- EX 1: SELECT PARA CONSULTAR TODAS AS COLUNAS
SELECT * FROM CLIENTE;

-- EX 2: CONSULTANDO POR CULUNAS
SELECT NOME, EMAIL FROM CLIENTE

-- EX 3: INSERINDO APELIDO NAS COLUNAS -- ALIAS
SELECT NOME AS CLIENTE
FROM CLIENTE;

SELECT NOME AS CLIENTE, TELEFONE AS CONTATO, ATIVO AS STATUS
FROM CLIENTE;

SELECT NOME, PRECO, PRECO * 0.90 AS PREÇO_PROMOCIONAL
FROM PRODUTO;

-- EX 4: DISTINCT - ELIMINAR REPETIÇÕES
SELECT CIDADE FROM CLIENTE;

SELECT DISTINCT CIDADE
FROM CLIENTE;
-- SEM DISTINCT O ITEM IRÁ APARECER VÁRIAS VEZES
-- COM DISTINCTO ITEM IRÁ APARECER APENAS UMA VEZ

--EX 5: FILTRO EM REGISTROS
SELECT NOME, PRECO
FROM PRODUTO
WHERE PRECO > 10;
-- RETORNA VALORES ACIMA DE 10 REAIS EM SEUS PREÇOS

SELECT NOME, PRECO
FROM CLIENTE
WHERE ATIVO = TRUE;
-- RETORNA PRODUTOS ATIVOS

SELECT ID_PEDIDO, DATA_PEDIDO, VALOR_TOTAL
FROM PEDIDO
WHERE VALOR_TOTAL >= 25.00;
-- RETORNA PEDIDOS ACIMA DE DETERMINADO VALOR

-- OPERADORES DE COMPARAÇÃO
-- = IGUAL
-- <> OU != DIFERENTE
-- > MAIOR QUE
-- >= MAIOR OU IGUAL 
-- < MENOR QUE
-- <= MENOR OU IGUAL

-- EX 6; USO DE AND, OR E NOT
-- AND - TODAS AS CONDIÇÕES PRECISAM SER VERDADEIRAS
SELECT NOME, PRECO
FROM produto
WHERE PRECO >= 8.00 AND PRECO <= 20.00;

-- OR - PELO MENOS UMA CONDIÇÃO VERDADEIRA
SELECT NOME, CIDADE
FROM CLIENTE WHERE CIDADE = 'LIMEIRA' OR CIDADE = 'PIRACICABA';

-- NOT - NEGAR NÃO TRAZER RESULTADO QUE FOI APRESENTADO
SELECT NOME, CIDADE
FROM CLIENTE
WHERE NOT CIDADE = 'LIMEIRA';

-- JUNTOS - AND E OR SEMPRE UTILIZAR ()
SELECT NOME, CIDADE, ATIVO AS STATUS
FROM CLIENTE
WHERE ATIVO = TRUE
AND (CIDADE = 'LIMEIRA' OR CIDADE = 'AMERICANA');

-- EX 7: PESQUISANOD POR INTERVALO - BETWEEN
SELECT NOME, PRECO
FROM PRODUTO
WHERE PRECO BETWEEN 8.00 AND 15.00;

SELECT ID_PEDIDO, DATA PEDIDO, VALOR_TOTAL
FROM PEDIDO
WHERE DATA_PEDIDO BETWEEN '2026-09-01 00:00:00' AND '2026-09-30 23:59:59';

-- EX 8: IN COM VÁRIAS POSSIBILIDADES
SELECT NOME, CIDADE
FROM CLIENTE
WHERE CIDADE IN ('LIMEIRA', 'AMERICANA', 'PIRACICABA');

SELECT NOME, CIDADE
FROM CLIENTE
WHERE CIDADE NOT IN ('LIMEIRA','CAMPINAS');

-- EX 9: EXEMPLO COM TEXTOS OU PESQUISAR POR TEXTOS - LIKE
-- CORINGAS
-- % VÁRIOS CARACTERES
-- _EXATAMENTE UM CARACTER

SELECT NOME 
FROM PRODUTO
WHERE NOME LIKE 'CAFÉ%';
-- RETORNAR PRODUTOS QUE POSSUEM A PALAVRA CAFÉ E QUE COMEÇAM COM ELA

SELECT NOME
FROM PRODUTO
WHERE NOME LIKE '%CHOCOLATE%'
-- RETORNAR PRODUTOS QUE POSSUEM A PALAVRA CHOCOLATE

SELECT NOME 
FROM PRODUTO
WHERE NOME LIKE '%SILVA';
-- RETORNAR NOMES QUE TERMINAM COM SILVA


SELECT NOME
FROM PRODUTO
WHERE NOME LIKE '_AFÉ';

-- EX 10: NULL - AUSÊNCIA DE VALOR
SELECT NOME, TELEFONE
FROM CLIENTE
WHERE TELEFONE IS NULL;

SELECT NOME, TELEFONE
FROM CLIENTE
WHERE TELEFONE IS NOT NULL;

-- EX 11: ORDER BY - ORDENAR RESULTADOS
-- ASC SIGNIFICA CRESCENTE
-- DESC SIGNIFICA DECRESCENTE
SELECT NOME, PRECO
FROM PRODUTO
ORDER BY PRECO DESC;

SELECT NOME, PRECO
FROM PRODUTO
ORDER BY PRECO DESC

SELECT CIDADE, NOME
FROM CLIENTE
ORDER BY CIDADE ASC, NOME DESC


--  EX 12: LIMIT - LIMITANDO A QUANTIDADE DE LINHA
SELECT NOME, PRECO
FROM PRODUTO
ORDER BY PRECO DESC
LIMIT 8;

SELECT NOME, PRECO
FROM PRODUTO
ORDER BY NOME
LIMIT 10 OFFSET 10;

-- EX 13: CÁLCULO DE COLUNAS
SELECT NOME, PRECO, PRECO * 1.10 AS PRECO_ATUALIZADO
FROM PRODUTO;

SELECT ID_ITEM, QUANTIDADE, PRECO_UNITARIO, QUANTIDADE * PRECO_UNITARIO AS TOTAL_COMPRA
FROM ITEM_PEDIDO;

-- EX 14: FUNÇÕES PARA CONSULTA
-- TEXTOS
SELECT UPPER(NOME) AS NOME_CLIENTE, LOWER(EMAIL) AS EMAIL
FROM CLIENTE;
SELECT CONCAT(NOME, ' - ', CIDADE) AS CLIENTE_CIDADE
FORM CLIENTE;

-- NÚMEROS
SELECT NOME, PRECO, ROUND(PRECO * 0.90, 2) AS PREÇO_DESCONTO
FROM PRODUTO;

--DATAS
SELECT ID_PEDIDO, DATA_PEDIDO, DATE(DATA_PEDIDO) AS DATAS, MONTH (DATA_PEDIDO) AS MêS, YEAR(DATA_PEDIDO) AS ANO
FROM PEDIDO;

-- SUBSTITUINDO O NULL NO RESULTADO
SELECT NOME, COALESCE(TELEFONE, 'NÃO INFORMADO') AS CONTATO
FROM CLIENTE;














































































































