-- COMANDO PARA CRIAR  BC
CREATE DATABASE ACADEMIA_JACO;
CREATE DATABASE IF NOT EXISTS ACADEMIA_JACO;

-- COMANDA PARA APAGAR BD
DROP DATABASE ACADEMIA_JACO;

-- ATUALIZAR SCHEMAS

-- COMANDO PARA ATIVAR BD
USE ACADEMIA_JACO;

-- COMANDO PARA APAGAR TABABELA
DROP DATABASE CLIENTE;

-- COMANDO CRIAR TABELA
CREATE TABLE CLIENTE (
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
CPF VARCHAR(14) NOT NULL UNIQUE, -- (NOT NULL) SIGINIFICA QUE O ITEM DO CAMPO TEM QUE SER PRENCHIDO. (UNIQUE) SIGINIFICA QUE O ATRIBUTO É UNICO
NOME VARCHAR(60) NOT NULL,
ENDERECO VARCHAR(100),
TELEFONE VARCHAR(20) NOT NULL,
STATUS_CLIENTE ENUM ('PENDENTE', 'ATIVO', 'INATIVO') DEFAULT "PENDENTE",
DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CLIENTE (
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
CPF VARCHAR(14) NOT NULL UNIQUE, -- (NOT NULL) SIGINIFICA QUE O ITEM DO CAMPO TEM QUE SER PRENCHIDO. (UNIQUE) SIGINIFICA QUE O ATRIBUTO É UNICO
NOME VARCHAR(60) NOT NULL,
ENDERECO VARCHAR(100),
TELEFONE VARCHAR(20) NOT NULL
);

-- COMANDOS PARA ALTERAR E CORRIGIR
-- ADICIONANDO UM CAMPO (ATRIBUTO) NOVO
ALTER TABLE CLENTE ADD EMAIL VARCHAR(100);

-- MODIFICAR TIPO DE DADOS OU CAMPOS
ALTER TABLE CLIENTES MODIFY EMAIL VARCHAR(150);

-- RENOMEAR TABELAS
RENAME TABLE CLIENTES TO CLENTES2;

-- EXCLUIR ATRIBUTO
ALTER TABLE CLIENTES DROP COLUMN EMAIL;

-- VISUALIZAR TABELAS NO BC
SHOW TABLES;

-- LIMPAR DADOS DA TABELA
TRUNCATE TABLE CLIENTE;


-- TIPO --
-- O (VARCHAR) É USADO PARA SE O ATRIBUTO É ESCRITO
-- O (CHAR) É A MESMA COISA, A DIFERENSA QUE É ALGO MAIS CURTO
-- O (DECIMAL) SERVE PARA COLOCAR VALOR
-- O (DATE) SERVE PARA COLOCAR SÓ A DATA
-- O (DATE TIME) SERVE PARA COLOCAR DATA E HORA
-- O (ENUM) SERVE PARA COISAS COMPOSTAS EXEMPLO - NO ATRIBUTO CLIENTE TEM O STATUS DELE TEM  (ATIVO, DESATIVO, PENDENTE)
-- O (DEFAULT) SERVE PARA FORÇAR UMA ESCOLHA OU DEIXAR ELA COMO PADRÃO CASO A PESSOA NÃO ESCOLHA
-- O (TIMESTAMP) BUSCA A DATA PADRÃO DO PAÍS QUE ESTEJA