-- CRIAR BANCO DE DADOS
CREATE DATABASE CASTELLO;

-- ATIVAR BANCO DE DADOS
USE CASTELLO;

-- CRIAR TABELAS
CREATE TABLE IF NOT EXISTS ALUNOS (
    ID_ALUNO BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (100) NOT NULL,
    CPF CHAR (14) NOT NULL UNIQUE,
    STATUS_ALUNO ENUM('ATIVO', 'INATIVO', 'CONCLUÍDO') DEFAULT 'ATIVO',
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- VISUALIZAR TODOS OS BANCO DE DADOS
SHOW SCHEMAS;

-- VISUALIZAR TABELAS DO BANCO DE DADOS
SHOW TABLES;

-- DESCRIÇÃO DE ATRIBUTOS DA TABELA ALUNOS
DESCRIBE ALUNOS;

-- DELETAR BANCO DE DADOS
DROP DATABASE CASTELLO;

-- DELETAR TABELA
DROP TABLE ALUNOS;