-- Active: 1788351678322@@127.0.0.1@3306@smartcoffee_dml_jacó
-- Lição do MSQL da Aula 8 23/09/2026

SMARTCOFFEE BASE DE DADOS - DML
EXECUTE SEMPRE QUE QUISER RESTAURAR A STATS_AUTO_RECALC

-- COMMANDO QUE SERVE PARA DELETAR UM DATABASE / BANCO DE DADOS
DROP DATABASE IF EXISTS SMARTCOFFEE_DML_JACO;

-- COMMANDO QUE SERVE PARA A CRIAÇÃO DO DATABASE / BANCO DE DADOS
CREATE DATABASE SMARTCOFFEE_DML_JACO;

--COMMANDO QUE SERVE PARA ATIVAR O DATABASE / BANCO DE DADOS
USE SMARTCOFFEE_DML_JACO;

CREATE TABLE CLIENTE (
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    -- O (NOT NULL) SERVE PARA QUE O CAMPO ESCOLHIDO SEJAQ OBRIGATORIO A SUA DIGITAÇÃO
    NOME VARCHAR(100) NOT NULL,
    -- O COMMANDO (UNIQUE) SERVE PARA QUE SÓ EXISTA 1 NESSE CAMPO, E QUE NÃO PODE SER REPTIDO
    EMAIL VARCHAR(120) UNIQUE,
    TELEFONE VARCHAR(20),
    CIDADE VARCHAR(60) NOT NULL,
    -- O COMMANDO (BOOLEAN) SERVE PARA TOMADAS DE VERDADEIRO E FALSO OU TRUE E FALSE
    -- O (DEFAULT) SERVE PARA FORÇAR UMA ESCOLHA
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE CATEGORIA (
    ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(60) NOT NULL
);


CREATE TABLE PRODUTO (
    ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL,
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    ID_CATEGORIA INT NOT NULL,
    -- O COMMANDO (CONSTRAINT) SERVE PARA MOSTRAR A A RELAÇÃO COM OUTRAS CATEGORIAS, PODENDO COLOCAR A CHAVE ESTRANGEIRA
    CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);

-- SERVE PARA DELETAR A TABELA PEDIDO
DROP TABLE IF EXISTS PEDIDO;


CREATE TABLE PEDIDO (
    ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    DATA_PEDIDO DATETIME NOT NULL,
    STATUS_PEDIDO ENUM('ABERTO', 'PREPARANDO', 'FINALIZADO', 'CANCELADO') NOT NULL, 
    VALOR_TOTAL DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ID_CLIENTE INT NOT NULL,
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE ITEM_PEDIDO (
    ID_ITEM INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    PRECO_UNITARIO DECIMAL(10,2) NOT NULL,
    -- ID_FORMA_PAGAMENTO INT NOT NULL,
    OBSERVACAO VARCHAR(100),
    -- VALOR DECIMAL(10,2) NOT NULL,
    DATA_PAGAMENTO DATETIME,
    CONSTRAINT FK_ITEM_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
    CONSTRAINT FK_ITEM_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);

DROP TABLE IF EXISTS ITEM_PEDIDO

CREATE TABLE FORMA_PAGAMENTO (
    ID_FORMA_PAGAMENTO INT PRIMARY KEY  AUTO_INCREMENT,
    DESCRICAO VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE PAGAMENTO (
    ID_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT NOT NULL,
    ID_FORMA_PAGAMENTO INT NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,
    DATA_PAGAMENTO DATETIME,
    CONSTRAINT FK_PAGAMENTO_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
    CONSTRAINT FK_PAGAMENTO_FORMA FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_FORMA_PAGAMENTO)
);

DROP TABLE IF EXISTS PAGAMENTO

-- DADOS INICIAIS
INSERT INTO CLIENTE (NOME, EMAIL, TELEFONE, CIDADE, ATIVO) VALUES
('ANNA CONCOLATO', 'ANNA@EMAIL.COM', '19999999991', 'LIMEIRA', TRUE),
('BRUNO SOUZA', 'BRUNO@EMAIL.COM', '19999999992', 'LIMEIRA', TRUE),
('CARLA MENDES', 'CARLA@EMAIL.COM', NULL , 'AMERICANA', TRUE),
('JACÓ SOUZA', 'JACÓ@EMAIL.COM', '19999999993', 'LIMEIRA', TRUE),
('GABRIELA LIMA', 'GABRIELA@EMAIL.COM', '19999999994', 'LIMEIRA', TRUE),
('JUAN PABLO', 'JUAN@EMAIL.COM', NULL , 'AMERICANA', TRUE),
('GUSTAVO COUTE', 'GUSTAVO@EMAIL.COM', '19999999995', 'LIMEIRA', TRUE),
('JONAS DAWVIN', 'JONAS@EMAIL.COM', '19999999996', 'LIMEIRA', FALSE),
('JHON WISK', 'JHON@EMAIL.COM', NULL , 'AMERICANA', TRUE),
('DAVI GUERRA', 'DAVI@EMAIL.COM', NULL , 'AMERICANA', TRUE);

SELECT * FROM CLIENTE;

-- INCERE INFORMAÇÕES NA TABELA ESCOLHIDA
INSERT INTO CATEGORIA (NOME) VALUES
('CAFÉS'), ('BEDIDAS GELADAS'),('DOCES'), ('SALGADOS'), ('COMBOS');

SELECT * FROM CATEGORIA;

INSERT INTO PRODUTO (NOME, PRECO, ATIVO, ID_CATEGORIA) VALUES
('CAFÉ ESPRESSO',7.00, TRUE, 1), ('CAFÉ DEPLO', 10.00, TRUE, 1),
('CAFÉ COM LEITE',9.50, TRUE, 1), ('CAPPUCCCINO', 13.00, TRUE, 1),
('BAILARINA CAPUTINO',7.00, TRUE, 1), ('CAPUTINO ASSASINO', 14.00, TRUE, 2),
('MONSTER COM CAFÉ', 18.00, TRUE, 3), ('MONSTER COM LEITE', 20.00, FALSE, 2),
('LEITE COM CAFÉ',17.00, TRUE, 1), ('LEITE COM LEITE', 30.00, TRUE, 1);

INSERT INTO PEDIDO (DATA_PEDIDO, STATUS_PEDIDO, VALOR_TOTAL, ID_CLIENTE) VALUES
('2026-09-01 08:15:00', 'FINALIZADO', 16.00, 1),
('2026-09-01 09:30:00', 'FINALIZADO', 26.00, 2),
('2026-09-01 10:15:00', 'FINALIZADO', 16.00, 3),
('2026-09-01 12:30:00', 'FINALIZADO', 26.00, 4),
('2026-09-01 14:15:00', 'FINALIZADO', 16.00, 1),
-- O COMMANDO (NOW) SERVE PARA REGISTRAR A DATA ATUAL DO COMPUTADOR
(NOW(), 'FINALIZADO', 16.00, 1);

-- AQUI ELE PEDE O ULTIMO ID CADASTRADO E PEDE PARA MOSTRAR
SET @PEDIDO = LAST_INSERT_ID();

SELECT @PEDIDO;

INSERT INTO ITEM_PEDIDO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE, PRECO_UNITARIO, OBSERVACAO) VALUES
(1,1,1,7.00,NULL),(1,9,1,9.00,NULL),(2,4,2,13.00,'SEM CANELA'),
(3,7,1,18.00,NULL),(4,5,1,15.00,NULL),(4,16,1,20.00,NULL);

INSERT INTO FORMA_PAGAMENTO (DESCRICAO) VALUES
('DINHEIRO'), ('PIX'), ('CARTÃO DE CRÉDITO'), ('CARTÃO DE DÉBITO');

INSERT INTO PAGAMENTO (ID_PEDIDO, ID_FORMA_PAGAMENTO, VALOR, DATA_PAGAMENTO) VALUES
(1,2,16.00,'2026-09-01 08:20:'),(2,4,26.00,'2026-09-01 09:48:00'),
(4,8,26.00,'2026-09-04 13:13:'),(5,2,26.00,'2026-09-04 16:48:00');

UPDATE CLIENTE
SET TELEFONE = '19999999123', 
    CIDADE = 'PIRACICABA'
WHERE ID_CLIENTE = 4;

-- EX 3 : ATUALIZANDO VÁRIOS REGISTROS
UPDATE PRODUTO
SET PRECO = PRECO * 1.05
WHERE ID_CATEGORIA = 1;

-- EX 4 : ATUALIZANDO SEM WHERE
-- UPDATE PRODUTO
-- SET PRECO = 1.00
-- CUIDADO AO UTILIZAR ESSA LINHA

-- EX 5 : ATUALIZANDO CONDICIONAIS

UPDATE PRODUTO
SET PRECO = CASE
    WHEN PRECO < 10 THEN PRECO * 1.10
    ELSE PRECO * 1.05
END
WHERE ATIVO = TRUE;

-- EX 6 : ATUALIZANDO PARA NULL
UPDATE PRODUTO
SET PRECO = CASCADE
    WHEN PRECO <= 15 THEN PRECO * 1.10
    ELSE PRECO * 1.05
END
WHERE ATIVO = TRUE;
