
-- TIPO --
-- O (VARCHAR) É USADO PARA SE O ATRIBUTO É ESCRITO
-- O (CHAR) É A MESMA COISA, A DIFERENSA QUE É ALGO MAIS CURTO
-- O (DECIMAL) SERVE PARA COLOCAR VALOR
-- O (DATE) SERVE PARA COLOCAR SÓ A DATA
-- O (DATE TIME) SERVE PARA COLOCAR DATA E HORA
-- O (ENUM) SERVE PARA COISAS COMPOSTAS EXEMPLO - NO ATRIBUTO CLIENTE TEM O STATUS DELE TEM  (ATIVO, DESATIVO, PENDENTE)
-- O (DEFAULT) SERVE PARA FORÇAR UMA ESCOLHA OU DEIXAR ELA COMO PADRÃO CASO A PESSOA NÃO ESCOLHA
-- O (TIMESTAMP) BUSCA A DATA PADRÃO DO PAÍS QUE ESTEJA

-- COMANDO PARA CRIAR  BC
CREATE DATABASE Oficina_jaco;


-- APAGAR BANCO DE DADOS

DROP DATABASE Oficina_jaco; 


-- COMANDO PARA ATIVAR BD
USE Oficina_jaco;

CREATE TABLE CLIENTE (
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
CPF VARCHAR(19) NOT NULL UNIQUE, 
NOME VARCHAR(50) NOT NULL,
TELEFONE VARCHAR(19) NOT NULL,
STATUS_CLIENTE ENUM ('ATENDIDO', 'NAO_ATENDIDO') DEFAULT "NAO_ATENDIDO",
ENDERECO VARCHAR(100) NOT NULL
);

CREATE TABLE VEICULOS (
ID_VEICULOS INT AUTO_INCREMENT PRIMARY KEY,
QUANTIDADE VARCHAR(200) NOT NULL, 
PRECO VARCHAR(12) NOT NULL,
DATA_CRIACAO DATE NOT NULL,
NOME VARCHAR(80) NOT NULL,
ESTOQUE ENUM ('EM_ESTOQUE', 'FORA_DE_ESTOQUE') DEFAULT "FORA_DE_ESTOQUE"
);

CREATE TABLE MARCAS (
ID_MARCAS INT AUTO_INCREMENT PRIMARY KEY,
LOCAL_DE_ORIGEM VARCHAR(30), 
CONTRATO VARCHAR (1000),
DATA_CRIACAO DATE,
NOME VARCHAR(50) NOT NULL,
QUALIDADE ENUM ('MUITO_BOA', 'NAO_MUITO_BOA') DEFAULT "NAO_MUITO_BOA"
);

CREATE TABLE MODELOS (
ID_MODELOS INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
ESTOQUE ENUM ('EM_ESTOQUE', 'FORA_DE_ESTOQUE') DEFAULT "FORA_DE_ESTOQUE",
TAMANHO VARCHAR(100), 
QUANTIDADE VARCHAR(1000) NOT NULL,
QUALIDADE ENUM ('MUITO_BOA', 'NAO_MUITO_BOA') DEFAULT "NAO_MUITO_BOA"
);

CREATE TABLE SERVICOS (
ID_SERVICOS INT AUTO_INCREMENT PRIMARY KEY,
HORARIO DATETIME NOT NULL,
FUNCAO VARCHAR(1000) NOT NULL,
SETOR VARCHAR(50) NOT NULL,
QUANTIDADE VARCHAR(100) NOT NULL,
STATUS_TRABALHO ENUM ('ENTREGUE', 'PENDENTE') DEFAULT "PENDENTE"
);

CREATE TABLE FORNECEDORES (
ID_FORNECEDORES INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
TELEFONE VARCHAR(19) NOT NULL,
EMAIL VARCHAR(50),
DATE_ENTREGA DATETIME NOT NULL,
QUANTIDADE VARCHAR(100)
);

CREATE TABLE PECAS(
ID_PECAS INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(80) NOT NULL,
QUANTIDADE VARCHAR(1000) NOT NULL,
DATE_CRIACAO DATE NOT NULL,
PECOS VARCHAR(12),
ESTOQUE ENUM ('EM_ESTOQUE', 'FORA_DE_ESTOQUE') DEFAULT "FORA_DE_ESTOQUE"
);

CREATE TABLE FUNCIONARIOS (
ID_FUNCIONARIOS INT AUTO_INCREMENT PRIMARY KEY,
CPF VARCHAR(19) NOT NULL UNIQUE, 
NOME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
TURNO DATETIME NOT NULL,
FUNCAO VARCHAR(100) NOT NULL
);

CREATE TABLE ORDENS_DE_SERVICO(
ID_ORDENS_DE_SERVICO INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
SETOR VARCHAR(50) NOT NULL,
HORARIO DATETIME NOT NULL,
FUNCAO VARCHAR(100) NOT NULL,
STATUS_PEDIDO ENUM ('CONCLUIDO', 'NAO_CONCLUIDO') DEFAULT "NAO_CONCLUIDO"
);

CREATE TABLE PAGAMENTOS(
ID_ORDENS_DE_SERVICO INT AUTO_INCREMENT PRIMARY KEY,
DATA_DO_PAGAMENTO DATETIME NOT NULL,
CPF VARCHAR(19) NOT NULL UNIQUE,
PRODUTOS VARCHAR(100) NOT NULL,
QUANTIDADE VARCHAR(100) NOT NULL,
FORMA_PAGAMENTO ENUM ('debito', 'credito' , 'pix' , 'dinheiro') DEFAULT "debito"
);
